Repository dieter-project/WithPT-BE, pull requests merged in 2023-11, with the labels that each got.

#83 fix(trainer) : 트레이너 가입 정보 수정
  src/main/java/com/sideproject/withpt/application/trainer/controller/request/AcademicRequest.java
  src/main/java/com/sideproject/withpt/application/trainer/controller/request/CareerRequest.java
  src/main/java/com/sideproject/withpt/application/trainer/controller/request/CertificateRequest.java
  src/main/java/com/sideproject/withpt/application/trainer/controller/request/EducationRequest.java
  src/main/java/com/sideproject/withpt/application/trainer/service/dto/single/AcademicDto.java
  src/main/java/com/sideproject/withpt/application/trainer/service/dto/single/CareerDto.java
  src/main/java/com/sideproject/withpt/application/trainer/service/dto/single/CertificateDto.java
  src/main/java/com/sideproject/withpt/application/trainer/service/dto/single/EducationDto.java
  src/main/java/com/sideproject/withpt/application/type/AcademicInstitution.java
  src/main/java/com/sideproject/withpt/application/type/Degree.java
  src/main/java/com/sideproject/withpt/application/type/EmploymentStatus.java
  src/main/java/com/sideproject/withpt/domain/trainer/Academic.java
  src/main/java/com/sideproject/withpt/domain/trainer/Career.java
  src/main/java/com/sideproject/withpt/domain/trainer/Certificate.java
  src/main/java/com/sideproject/withpt/domain/trainer/Education.java
Labels: ✨ Feature, ✅ Test

#87 fix(Academic) : 트레이너 학력사항 대학 기관 별 CRUD 수정
  src/main/java/com/sideproject/withpt/application/academic/controller/AcademicController.java
  src/main/java/com/sideproject/withpt/application/academic/controller/request/AcademicEditRequest.java
  src/main/java/com/sideproject/withpt/application/academic/controller/request/AcademicSaveRequest.java
  src/main/java/com/sideproject/withpt/application/academic/controller/response/AcademicResponse.java
  src/main/java/com/sideproject/withpt/application/academic/repository/AcademicQueryRepository.java
  src/main/java/com/sideproject/withpt/application/academic/service/AcademicQueryService.java
  src/main/java/com/sideproject/withpt/domain/trainer/Academic.java
  src/test/java/com/sideproject/withpt/application/academic/service/AcademicQueryServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#89 feat(Award) : 수상 내역 기본 CRUD
  src/main/java/com/sideproject/withpt/application/award/controller/AwardController.java
  src/main/java/com/sideproject/withpt/application/award/controller/reponse/AwardResponse.java
  src/main/java/com/sideproject/withpt/application/award/controller/request/AwardEditRequest.java
  src/main/java/com/sideproject/withpt/application/award/controller/request/AwardSaveRequest.java
  src/main/java/com/sideproject/withpt/application/award/exception/AwardErrorCode.java
  src/main/java/com/sideproject/withpt/application/award/exception/AwardException.java
  src/main/java/com/sideproject/withpt/application/award/repository/AwardQueryRepository.java
  src/main/java/com/sideproject/withpt/application/award/repository/AwardRepository.java
  src/main/java/com/sideproject/withpt/application/award/service/AwardQueryService.java
  src/main/java/com/sideproject/withpt/domain/trainer/Award.java
Labels: ✨ Feature

#91 feat(Education) : 트레이너 교육 내역 CRUD
  src/main/java/com/sideproject/withpt/application/education/controller/EducationController.java
  src/main/java/com/sideproject/withpt/application/education/controller/reponse/EducationResponse.java
  src/main/java/com/sideproject/withpt/application/education/controller/request/EducationEditRequest.java
  src/main/java/com/sideproject/withpt/application/education/controller/request/EducationSaveRequest.java
  src/main/java/com/sideproject/withpt/application/education/exception/EducationErrorCode.java
  src/main/java/com/sideproject/withpt/application/education/exception/EducationException.java
  src/main/java/com/sideproject/withpt/application/education/repository/EducationQueryRepository.java
  src/main/java/com/sideproject/withpt/application/education/repository/EducationRepository.java
  src/main/java/com/sideproject/withpt/application/education/service/EducationQueryService.java
  src/main/java/com/sideproject/withpt/domain/trainer/Education.java
Labels: ✨ Feature

#93 fix(Certificate) : 트레이너 자격증 기관명 추가
  src/main/java/com/sideproject/withpt/application/certificate/controller/CertificateController.java
  src/main/java/com/sideproject/withpt/application/certificate/controller/reponse/CertificateResponse.java
  src/main/java/com/sideproject/withpt/application/certificate/controller/request/CertificateEditRequest.java
  src/main/java/com/sideproject/withpt/application/certificate/controller/request/CertificateSaveRequest.java
  src/main/java/com/sideproject/withpt/application/certificate/repository/CertificateQueryRepository.java
  src/main/java/com/sideproject/withpt/application/certificate/service/CertificateQueryService.java
  src/main/java/com/sideproject/withpt/domain/trainer/Certificate.java
Labels: 🔨 Refactor

#96 fix(member) : 회원 회원가입 파라미터 수정
  src/main/java/com/sideproject/withpt/application/member/controller/MemberAuthenticationController.java
  src/main/java/com/sideproject/withpt/application/member/dto/request/MemberSignUpRequest.java
  src/main/java/com/sideproject/withpt/application/member/service/MemberAuthenticationService.java
  src/main/java/com/sideproject/withpt/application/type/ExerciseFrequency.java
  src/main/java/com/sideproject/withpt/domain/member/Member.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#97 #54 exercise image upload
  src/main/java/com/sideproject/withpt/application/exercise/controller/BookmarkController.java
  src/main/java/com/sideproject/withpt/application/exercise/controller/ExerciseController.java
  src/main/java/com/sideproject/withpt/application/exercise/dto/request/ExerciseRequest.java
  src/main/java/com/sideproject/withpt/application/exercise/dto/response/BookmarkCheckResponse.java
  src/main/java/com/sideproject/withpt/application/exercise/dto/response/BookmarkResponse.java
  src/main/java/com/sideproject/withpt/application/exercise/dto/response/ExerciseListResponse.java
  src/main/java/com/sideproject/withpt/application/exercise/dto/response/ExerciseResponse.java
  src/main/java/com/sideproject/withpt/application/exercise/exception/ExerciseErrorCode.java
  src/main/java/com/sideproject/withpt/application/exercise/exception/ExerciseException.java
  src/main/java/com/sideproject/withpt/application/exercise/repository/BookmarkRepository.java
  src/main/java/com/sideproject/withpt/application/exercise/repository/ExerciseRepository.java
  src/main/java/com/sideproject/withpt/application/exercise/service/BookmarkService.java
  src/main/java/com/sideproject/withpt/application/exercise/service/ExerciseService.java
  src/main/java/com/sideproject/withpt/application/image/ImageUploader.java
  src/main/java/com/sideproject/withpt/application/image/repository/ImageRepository.java
  src/main/java/com/sideproject/withpt/application/type/Usages.java
  src/main/java/com/sideproject/withpt/common/exception/CommonErrorCode.java
  src/main/java/com/sideproject/withpt/common/exception/GlobalException.java
  src/main/java/com/sideproject/withpt/domain/record/Bookmark.java
  src/main/java/com/sideproject/withpt/domain/record/Exercise.java
  src/main/java/com/sideproject/withpt/domain/record/Image.java
  src/test/java/com/sideproject/withpt/application/exercise/service/BookmarkServiceTest.java
  src/test/java/com/sideproject/withpt/application/exercise/service/ExerciseServiceTest.java
Labels: ✨ Feature, ✅ Test

#99 feat(body) : 눈바디 이미지 업로드
  src/main/java/com/sideproject/withpt/application/body/controller/BodyController.java
  src/main/java/com/sideproject/withpt/application/body/dto/request/BodyInfoRequest.java
  src/main/java/com/sideproject/withpt/application/body/dto/request/WeightInfoRequest.java
  src/main/java/com/sideproject/withpt/application/body/dto/response/BodyImageResponse.java
  src/main/java/com/sideproject/withpt/application/body/dto/response/WeightInfoResponse.java
  src/main/java/com/sideproject/withpt/application/body/repository/BodyCustomRepository.java
  src/main/java/com/sideproject/withpt/application/body/repository/BodyCustomRepositoryImpl.java
  src/main/java/com/sideproject/withpt/application/body/service/BodyService.java
  src/main/java/com/sideproject/withpt/application/exercise/controller/BookmarkController.java
  src/main/java/com/sideproject/withpt/application/exercise/controller/ExerciseController.java
  src/main/java/com/sideproject/withpt/application/exercise/service/ExerciseService.java
  src/main/java/com/sideproject/withpt/application/image/ImageUploader.java
  src/main/java/com/sideproject/withpt/application/image/repository/ImageCustomRepository.java
  src/main/java/com/sideproject/withpt/application/image/repository/ImageCustomRepositoryImpl.java
  src/main/java/com/sideproject/withpt/application/image/repository/ImageRepository.java
  src/main/java/com/sideproject/withpt/common/exception/CommonErrorCode.java
  src/main/java/com/sideproject/withpt/domain/record/Body.java
  src/test/java/com/sideproject/withpt/application/body/service/BodyServiceTest.java
  src/test/java/com/sideproject/withpt/application/exercise/service/ExerciseServiceTest.java
Labels: ✨ Feature, ✅ Test

#100 feat(diet) : 식단 입력/수정/삭제 기능 구현
  src/main/java/com/sideproject/withpt/application/diet/controller/DietController.java
  src/main/java/com/sideproject/withpt/application/diet/dto/request/DietRequest.java
  src/main/java/com/sideproject/withpt/application/diet/dto/request/FoodItemRequest.java
  src/main/java/com/sideproject/withpt/application/diet/dto/response/DietResponse.java
  src/main/java/com/sideproject/withpt/application/diet/exception/DietErrorCode.java
  src/main/java/com/sideproject/withpt/application/diet/exception/DietException.java
  src/main/java/com/sideproject/withpt/application/diet/repository/DietRepository.java
  src/main/java/com/sideproject/withpt/application/diet/repository/FoodItemRepository.java
  src/main/java/com/sideproject/withpt/application/diet/service/DietService.java
  src/main/java/com/sideproject/withpt/application/type/MealCategory.java
  src/main/java/com/sideproject/withpt/domain/record/Diets.java
  src/main/java/com/sideproject/withpt/domain/record/Food.java
  src/main/java/com/sideproject/withpt/domain/record/FoodItem.java
  src/test/java/com/sideproject/withpt/application/diets/service/DietServiceTest.java
Labels: ✨ Feature, ✅ Test

#105 fix(PT) : PT 등록 여부에 따른 센터별 회원 리스트 수정
  src/main/java/com/sideproject/withpt/application/pt/controller/GymPersonalTrainingController.java
  src/main/java/com/sideproject/withpt/application/pt/controller/response/EachGymMemberListResponse.java
  src/main/java/com/sideproject/withpt/application/pt/repository/PersonalTrainingQueryRepository.java
  src/main/java/com/sideproject/withpt/application/pt/service/PersonalTrainingService.java
  src/main/java/com/sideproject/withpt/application/type/PtRegistrationStatus.java
  src/main/java/com/sideproject/withpt/domain/pt/PersonalTraining.java
Labels: ✨ Feature, 🔨 Refactor

#109 fix(Member) : 회원 가입 시 회원 식단 Type 및 응답 형식 수정
  src/main/java/com/sideproject/withpt/application/type/DietType.java
Labels: 🔨 Refactor, ✅ Test
