Repository dieter-project/WithPT-BE, pull requests merged in 2023-10, with the labels that each got.

#58 fix(deploy) : 배포 과정 DB Dialect 미 포함 오류 수정
  build.gradle
Labels: 🐞 BugFix

#60 fix(auth) : kakao auth secret 코드 미포함 401 Unauthorized
  src/main/java/com/sideproject/withpt/application/auth/infra/google/GoogleClient.java
  src/main/java/com/sideproject/withpt/application/auth/infra/kakao/KakaoClient.java
Labels: 🐞 BugFix

#61 feat : 체육관 조회 및 회원 PT 목록 조회
  src/main/java/com/sideproject/withpt/application/pt/controller/GymPersonalTrainingController.java
  src/main/java/com/sideproject/withpt/application/pt/controller/request/PersonalTrainingMemberRequest.java
  src/main/java/com/sideproject/withpt/application/pt/controller/response/GymsAndNumberOfMembersResponse.java
  src/main/java/com/sideproject/withpt/application/pt/controller/response/PersonalTrainingMemberResponse.java
  src/main/java/com/sideproject/withpt/application/pt/exception/PTErrorCode.java
  src/main/java/com/sideproject/withpt/application/pt/exception/PTException.java
  src/main/java/com/sideproject/withpt/application/pt/repository/PersonalTrainingQueryRepository.java
  src/main/java/com/sideproject/withpt/application/pt/repository/PersonalTrainingRepository.java
  src/main/java/com/sideproject/withpt/application/pt/repository/dto/GymMemberCountDto.java
  src/main/java/com/sideproject/withpt/application/pt/repository/dto/PtMemberListDto.java
  src/main/java/com/sideproject/withpt/application/pt/service/PersonalTrainingService.java
  src/main/java/com/sideproject/withpt/application/type/PTInfoInputStatus.java
  src/main/java/com/sideproject/withpt/application/type/PtRegistrationAllowedStatus.java
  src/main/java/com/sideproject/withpt/application/type/PtRegistrationStatus.java
  src/main/java/com/sideproject/withpt/config/SecurityConfig.java
  src/main/java/com/sideproject/withpt/domain/gym/Gym.java
  src/main/java/com/sideproject/withpt/domain/gym/GymTrainer.java
  src/main/java/com/sideproject/withpt/domain/member/Member.java
  src/main/java/com/sideproject/withpt/domain/pt/PersonalTraining.java
  src/main/java/com/sideproject/withpt/domain/pt/PersonalTrainingInfo.java
  src/test/java/com/sideproject/withpt/application/pt/service/PersonalTrainingServiceTest.java
Labels: ✨ Feature

#66 fix(auth) : google 인증 redirect_uri 누락 코드 추가
  src/main/java/com/sideproject/withpt/application/auth/infra/google/GoogleClient.java
Labels: 🐞 BugFix

#67 feat : google code log 추가
  src/main/java/com/sideproject/withpt/application/auth/infra/google/GoogleClient.java
  src/main/java/com/sideproject/withpt/application/auth/infra/google/GoogleLoginParams.java
  src/main/java/com/sideproject/withpt/application/auth/infra/kakao/KakaoLoginParams.java
Labels: 🐞 BugFix

#71 fix(Trainer) : 트레이너 회원 가입 시 경력 사항 직책 항목 추가
  src/main/java/com/sideproject/withpt/application/trainer/controller/TrainerAuthenticationController.java
  src/main/java/com/sideproject/withpt/application/trainer/controller/request/AcademicRequest.java
  src/main/java/com/sideproject/withpt/application/trainer/controller/request/AwardRequest.java
  src/main/java/com/sideproject/withpt/application/trainer/controller/request/CareerRequest.java
  src/main/java/com/sideproject/withpt/application/trainer/controller/request/CertificateRequest.java
  src/main/java/com/sideproject/withpt/application/trainer/controller/request/EducationRequest.java
  src/main/java/com/sideproject/withpt/application/trainer/controller/request/TrainerGymScheduleRequest.java
  src/main/java/com/sideproject/withpt/application/trainer/controller/request/TrainerSignUpRequest.java
  src/main/java/com/sideproject/withpt/application/trainer/controller/request/WorkScheduleRequest.java
  src/main/java/com/sideproject/withpt/application/trainer/service/dto/single/CareerDto.java
  src/main/java/com/sideproject/withpt/application/type/Day.java
  src/main/java/com/sideproject/withpt/common/exception/validator/EnumValidator.java
  src/main/java/com/sideproject/withpt/common/exception/validator/YearMonthType.java
  src/main/java/com/sideproject/withpt/common/exception/validator/YearMonthValidator.java
  src/main/java/com/sideproject/withpt/common/exception/validator/YearType.java
  src/main/java/com/sideproject/withpt/common/exception/validator/YearValidator.java
  src/main/java/com/sideproject/withpt/domain/trainer/Career.java
Labels: 🐞 BugFix, ✨ Feature

#63 feat(PT) : 체육관 회원 해제 기능
  src/main/java/com/sideproject/withpt/application/member/repository/MemberRepository.java
  src/main/java/com/sideproject/withpt/application/member/service/MemberService.java
  src/main/java/com/sideproject/withpt/application/pt/controller/GymPersonalTrainingController.java
  src/main/java/com/sideproject/withpt/application/pt/controller/request/RemovePtMembersRequest.java
  src/main/java/com/sideproject/withpt/application/pt/exception/PTErrorCode.java
  src/main/java/com/sideproject/withpt/application/pt/exception/PTException.java
  src/main/java/com/sideproject/withpt/application/pt/repository/PersonalTrainingQueryRepository.java
  src/main/java/com/sideproject/withpt/application/pt/service/PersonalTrainingService.java
  src/test/java/com/sideproject/withpt/application/pt/service/PersonalTrainingServiceTest.java
Labels: ✨ Feature, ✅ Test

#72 #44 weight
  src/main/java/com/sideproject/withpt/application/body/controller/BodyController.java
  src/main/java/com/sideproject/withpt/application/body/dto/request/BodyInfoRequest.java
  src/main/java/com/sideproject/withpt/application/body/dto/request/WeightInfoRequest.java
  src/main/java/com/sideproject/withpt/application/body/dto/response/WeightInfoResponse.java
  src/main/java/com/sideproject/withpt/application/body/exception/BodyErrorCode.java
  src/main/java/com/sideproject/withpt/application/body/exception/BodyException.java
  src/main/java/com/sideproject/withpt/application/body/repository/BodyCustomRepository.java
  src/main/java/com/sideproject/withpt/application/body/repository/BodyCustomRepositoryImpl.java
  src/main/java/com/sideproject/withpt/application/body/repository/BodyRepository.java
  src/main/java/com/sideproject/withpt/application/body/service/BodyService.java
  src/main/java/com/sideproject/withpt/application/exercise/controller/ExerciseController.java
  src/main/java/com/sideproject/withpt/domain/member/Member.java
  src/main/java/com/sideproject/withpt/domain/record/Body.java
  src/test/java/com/sideproject/withpt/application/body/service/BodyServiceTest.java
  src/test/java/com/sideproject/withpt/application/exercise/service/BookmarkServiceTest.java
  src/test/java/com/sideproject/withpt/application/exercise/service/ExerciseServiceTest.java
Labels: ✨ Feature, ✅ Test

#74 feat(Career) : 트레이너 마이페이지 경력 CRUD
  src/main/java/com/sideproject/withpt/application/career/controller/CareerController.java
  src/main/java/com/sideproject/withpt/application/career/controller/request/CareerEditRequest.java
  src/main/java/com/sideproject/withpt/application/career/controller/response/CareerResponse.java
  src/main/java/com/sideproject/withpt/application/career/exception/CareerErrorCode.java
  src/main/java/com/sideproject/withpt/application/career/exception/CareerException.java
  src/main/java/com/sideproject/withpt/application/career/repository/CareerQueryRepository.java
  src/main/java/com/sideproject/withpt/application/career/repository/CareerRepository.java
  src/main/java/com/sideproject/withpt/application/career/service/CareerQueryService.java
  src/main/java/com/sideproject/withpt/domain/trainer/Career.java
  src/test/java/com/sideproject/withpt/application/career/service/CareerQueryServiceTest.java
Labels: ✨ Feature, ✅ Test

#77 feat(member) : FE 테스트를 위한 회원 탈퇴 임시 개발 및 배포
  src/main/java/com/sideproject/withpt/application/member/controller/MemberAuthenticationController.java
  src/main/java/com/sideproject/withpt/application/member/dto/request/MemberSignUpRequest.java
  src/main/java/com/sideproject/withpt/application/member/repository/MemberQueryRepositoryImpl.java
  src/main/java/com/sideproject/withpt/application/member/service/MemberAuthenticationService.java
Labels: ✨ Feature

#79 feat(Academic) : 트레이너 마이페이지 학력사항 CRUD
  src/main/java/com/sideproject/withpt/application/academic/controller/AcademicController.java
  src/main/java/com/sideproject/withpt/application/academic/controller/request/AcademicEditRequest.java
  src/main/java/com/sideproject/withpt/application/academic/controller/request/AcademicSaveRequest.java
  src/main/java/com/sideproject/withpt/application/academic/controller/response/AcademicResponse.java
  src/main/java/com/sideproject/withpt/application/academic/exception/AcademicErrorCode.java
  src/main/java/com/sideproject/withpt/application/academic/exception/AcademicException.java
  src/main/java/com/sideproject/withpt/application/academic/repository/AcademicQueryRepository.java
  src/main/java/com/sideproject/withpt/application/academic/repository/AcademicRepository.java
  src/main/java/com/sideproject/withpt/application/academic/service/AcademicQueryService.java
  src/main/java/com/sideproject/withpt/domain/trainer/Academic.java
  src/test/java/com/sideproject/withpt/application/academic/service/AcademicQueryServiceTest.java
Labels: ✨ Feature, ✅ Test

#81 feat(Certificate) : 트레이너 마이페이지 자격증 CRUD
  src/main/java/com/sideproject/withpt/application/academic/controller/request/AcademicEditRequest.java
  src/main/java/com/sideproject/withpt/application/career/controller/request/CareerEditRequest.java
  src/main/java/com/sideproject/withpt/application/certificate/controller/CertificateController.java
  src/main/java/com/sideproject/withpt/application/certificate/controller/reponse/CertificateResponse.java
  src/main/java/com/sideproject/withpt/application/certificate/controller/request/CertificateEditRequest.java
  src/main/java/com/sideproject/withpt/application/certificate/controller/request/CertificateSaveRequest.java
  src/main/java/com/sideproject/withpt/application/certificate/exception/CertificateErrorCode.java
  src/main/java/com/sideproject/withpt/application/certificate/exception/CertificateException.java
  src/main/java/com/sideproject/withpt/application/certificate/repository/CertificateQueryRepository.java
  src/main/java/com/sideproject/withpt/application/certificate/repository/CertificateRepository.java
  src/main/java/com/sideproject/withpt/application/certificate/service/CertificateQueryService.java
  src/main/java/com/sideproject/withpt/domain/trainer/Certificate.java
  src/test/java/com/sideproject/withpt/application/certificate/service/CertificateQueryServiceTest.java
  src/test/java/com/sideproject/withpt/common/exception/validator/EnumValidatorTest.java
Labels: ✨ Feature, ✅ Test
