Repository dieter-project/WithPT-BE, pull requests merged in 2023-12, with the labels that each got.

#111 feat(diet): 스프링 배치 재실행 대상 설정 수정
  src/main/java/com/sideproject/withpt/common/batch/FileReaderJobConfig.java
Labels: 🐞 BugFix

#113 feat(pt, gym) : 체육관 목록 페이징 조회
  src/main/java/com/sideproject/withpt/application/gym/controller/GymController.java
  src/main/java/com/sideproject/withpt/application/gym/repositoy/GymQueryRepository.java
  src/main/java/com/sideproject/withpt/application/gym/service/GymQueryService.java
  src/main/java/com/sideproject/withpt/application/pt/controller/GymPersonalTrainingController.java
  src/main/java/com/sideproject/withpt/application/pt/controller/response/CountOfMembersAndGymsResponse.java
  src/main/java/com/sideproject/withpt/application/pt/controller/response/GymsAndNumberOfMembersResponse.java
  src/main/java/com/sideproject/withpt/application/pt/controller/response/TotalPtsCountResponse.java
  src/main/java/com/sideproject/withpt/application/pt/repository/PersonalTrainingQueryRepository.java
  src/main/java/com/sideproject/withpt/application/pt/service/PersonalTrainingService.java
Labels: ✨ Feature

#116 feat(PT) : PT 등록 요청 알림 허용
  src/main/java/com/sideproject/withpt/application/pt/controller/GymPersonalTrainingController.java
  src/main/java/com/sideproject/withpt/application/pt/controller/request/AcceptPtRegistrationRequest.java
  src/main/java/com/sideproject/withpt/application/pt/exception/PTErrorCode.java
  src/main/java/com/sideproject/withpt/application/pt/exception/PTException.java
  src/main/java/com/sideproject/withpt/application/pt/service/PersonalTrainingService.java
  src/main/java/com/sideproject/withpt/domain/pt/PersonalTraining.java
Labels: ✨ Feature

#118 fix : pt 등록에 대한 응답은 따로 없으므로 void로 변경
  src/main/java/com/sideproject/withpt/application/pt/controller/GymPersonalTrainingController.java
Labels: ✨ Feature

#124 fix(회원관리) : PT 회원 관리 API 전체 검토 및 PT ID 추가
  src/main/java/com/sideproject/withpt/application/pt/controller/GymPersonalTrainingController.java
  src/main/java/com/sideproject/withpt/application/pt/controller/request/ExtendPtRequest.java
  src/main/java/com/sideproject/withpt/application/pt/controller/request/RemovePtMembersRequest.java
  src/main/java/com/sideproject/withpt/application/pt/controller/request/SavePtMemberDetailInfoRequest.java
  src/main/java/com/sideproject/withpt/application/pt/controller/response/MemberDetailInfoResponse.java
  src/main/java/com/sideproject/withpt/application/pt/controller/response/TotalAndRemainingPtCountResponse.java
  src/main/java/com/sideproject/withpt/application/pt/repository/PersonalTrainingQueryRepository.java
  src/main/java/com/sideproject/withpt/application/pt/repository/dto/PtMemberListDto.java
  src/main/java/com/sideproject/withpt/application/pt/service/PersonalTrainingService.java
  src/main/java/com/sideproject/withpt/domain/pt/PTCountLog.java
Labels: 🔨 Refactor
